### ISSUE TITLE
class Keyboard_' has no member named 'press'...

### ISSUE THREAD

**Issue by mherke** [nsedat/KeyboardDE#1]
i just tried the new custom firmware (german). i replaced "#include "KeyboardUK.h" by "#include "KeyboardDE.h" in "Touch_Pad_V4.1.ino" and get plenty of errors (class Keyboard_' has no member named 'press') when compiling from "TouchPad.h". Any ideas how to fix this?
Compiling with the UK Keyboard files is possible without any errors.

with kind regards

Michael

**Comment by nsedat** [comment]
Thanks Michael,

I fixed that stupid bug ...

cheers,
   Niels
